# Generated by Django 5.0.6 on 2024-06-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoCabecera',
            fields=[
                ('id_ingreso_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=255)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
