# Generated by Django 5.0.6 on 2024-06-14 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_cabecera', '0001_initial'),
        ('ingreso_detalle', '0001_initial'),
        ('tipo_pago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoDetalle',
            fields=[
                ('id_ingreso_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=255)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_ingreso_cabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingreso_cabecera.ingresocabecera')),
                ('id_tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_pago.tipopago')),
            ],
        ),
        migrations.DeleteModel(
            name='IngresoCabecera',
        ),
    ]
