# Generated by Django 5.0.6 on 2024-07-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_detalle', '0002_ingresodetalle_delete_ingresocabecera'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresodetalle',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
