# Generated by Django 5.0.6 on 2024-07-03 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso_usuario', '0001_initial'),
        ('tipo_usuario', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_permiso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='permiso_usuario.permisousuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id_tipoUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tipo_usuario.tipousuario'),
            preserve_default=False,
        ),
    ]
