# Generated by Django 5.0.6 on 2024-07-13 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_id_permiso_remove_user_id_tipousuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
