# Generated by Django 5.0.6 on 2024-09-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
