# Generated by Django 5.0.6 on 2024-07-01 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inmueble', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitante',
            fields=[
                ('id_habitante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmueble.inmueble')),
            ],
        ),
    ]
