# Generated by Django 5.0.6 on 2024-09-14 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabecera', '0001_initial'),
        ('gasto', '0002_gasto_importe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_cabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cabecera.cabecera')),
                ('id_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasto.gasto')),
            ],
        ),
    ]
