# Generated by Django 5.0.6 on 2024-06-10 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_persons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persons',
            new_name='Person',
        ),
    ]
