# Generated by Django 5.0.6 on 2024-06-10 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_persons_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='apell',
            new_name='surename',
        ),
    ]
