# Generated by Django 5.0.6 on 2024-09-14 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitante', '0001_initial'),
        ('inmueble', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabecera',
            fields=[
                ('id_cabecera', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_habitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitante.habitante')),
                ('id_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmueble.inmueble')),
            ],
        ),
    ]
