# Generated by Django 5.0.6 on 2024-07-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopago',
            name='tipo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
